version: '3.8'

services:
  xiaozhi-web:
    build: .
    container_name: xiaozhi-web
    ports:
      - "5001:5001"  # Web服务端口
      - "5002:5002"  # WebSocket代理端口
    environment:
      - WS_URL=ws://your_server_address:9005  # 替换为你的服务器地址
      - DEVICE_TOKEN=your_token               # 替换为你的设备令牌
      - WEB_PORT=5001
      - PROXY_PORT=5002
    volumes:
      - ./.env:/app/.env:ro  # 如果你想使用本地的.env文件
    restart: unless-stopped
    networks:
      - xiaozhi-net

networks:
  xiaozhi-net:
    driver: bridge 